baseurl: "/"
url: "http://avevox.github.io"

# Website settings
title: "AVEVOX"
description: "Ave Vow new website"
keywords: "Ave, Vox, design, print, avevox, products"
baseurl: "/"
url: "http://www.avevox.bg"

# author
author:
  name: 'AveVox'
  email: 'office@avevox.bg'

# landing page
landing:
  about: 'We are'
  projects: 'Clients'
  link: 'Contact'


# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
